
cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: "2"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "5"
max-status-checks-per-second: "5"
local-cores: 1
latency-wait: "15"
use-conda: "False"
use-singularity: "True"
use-envmodules: "True"
jobs: "64"
printshellcmds: "True"

# Example resource configuration
default-resources:
   - runtime=180
   - mem_mb=64000
   - partition=single
   - threads=128
# # set-threads: map rule names to threads
# set-threads:
#   - single_core_rule=1
#   - multi_core_rule=10
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
