methods:
    celloracle:
        k: 20
        thr_coaccess: 0.8
        ext: 500000
        fpr: 0.02
        blen: 200
        tfb_thr: 10
        a: 10
        p: 0.001
        n: 2000
    figr:
        ext: 500000
        thr_p2g_pval: 0.1
        ncres: 10
        cellK: 10
        dorcK: 10
        thr_score: 2
    granie:
        ext: 500000
        thr_fdr: 0.2
    pando:
        exclude_exons: 'TRUE'
        ext: 500000
        thr_corr: 0.05
        p_thresh: 0.1
        rsq_thresh: 0.05
        nvar_thresh: 2
        min_genes_per_module: 3

colors:
    nets:
        celloracle: '#1f77b4'
        figr: '#ff7f0e'
        granie: '#2ca02c'
        pando: '#d62728'
        random: 'black'
        collectri: '#9467bd'
        dorothea: '#8c564b'

# Datasets
datasets:
    pbmc10k:
        organism: 'hg38'
        url:
            matrix: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5'
            peak_annot: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_peak_annotation.tsv'
            atac_frags: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz'
            atac_index: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz.tbi'
        cases:
            tcell:
                celltypes: 'CD4 TCM;CD4 Naive;CD8 Naive;Treg;CD4 TEM;MAIT;CD8 TEM_1;CD8 TEM_2;gdT;CD8 TEM_2'
                n_hvg: 2048
                n_hvr: 16384
            bcell:
                celltypes: 'Naive B;Intermediate B;Memory B'
                n_hvg: 4096
                n_hvr: 16384
                root: 'Naive B'
            mono:
                celltypes: 'CD14 Mono;CD16 Mono'
                n_hvg: 4096
                n_hvr: 16384
                root: 'CD14 Mono'
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    reprofibro:
        organism: 'hg38'
        url:
            tar: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file'
            barcodes: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file&file=GSE242419%5Fmultiome%2EATAC%2ERNA%2Ebarcode%2Emap%2Etsv%2Egz'
            genes: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file&file=GSE242419%5Fmultiome%5Fgenes%2Etsv%2Egz'
            annot: 'https://zenodo.org/records/8313962/files/multiome.zip?download=1'
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
                root: 'Fibroblast-like'
    pitupair:
        organism: 'hg38'
        url:
            frags: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391776/suppl/GSM5391776%5FHF1M%2DCryo%5Fatac%5Ffragments%2Etsv%2Egz'
            multi: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391776/suppl/GSM5391776%5FHF1M%2DCryo%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    pitunpair:
        organism: 'hg38'
        url:
            atac_frags: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391768/suppl/GSM5391768%5FHFA1P%5Ffragments%2Etsv%2Egz'
            peaks: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391768/suppl/GSM5391768%5FHFA1P%5Ffiltered%5Fpeak%5Fbc%5Fmatrix%2Eh5'
            rna_mtx: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391775/suppl/GSM5391775%5FHF1P%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            atac_meta: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391768/suppl/GSM5391768%5FHFA1P%5Fsinglecell%2Ecsv%2Egz'
            celltypes: 'https://heibox.uni-heidelberg.de/f/d36511f7f94947859564/?dl=1'
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    heartatlas:
        organism: 'hg38'
        url:
            tar: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/fragments.tar'
            anndata: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/Global_raw.h5ad'
            annotation: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/Adult_Peaks.h5ad'
        batchIDs:
            - HCAHeartST10773166_HCAHeartST10781063
            - HCAHeartST10773165_HCAHeartST10781062
            - HCAHeart9508627_HCAHeart9508819
            - HCAHeart9508629_HCAHeart9508821
            - HCAHeart9845431_HCAHeart9917173
            - HCAHeartST11064575_HCAHeartST11023240
            - HCAHeartST11064574_HCAHeartST11023239
        cases:
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    brain:
        organism: 'hg38'
        url:
            full_dataset: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE193688&format=file'
            annot: 'https://heibox.uni-heidelberg.de/f/05637a872a384155a951/?dl=1'
        samples: 
            ['C5410', 'C4176', 'YC5928', 'C16007', 'C4322', 'YC5276', 'C4361', 'YC5346', 'C4660', 'YC5813', 'YC5442', 
            'YC914', 'YC5626', 'C4814', 'YC6235', 'C4634', 'YC4345', 'C4691', 'YC5751', 'P02284', 'P4205', 'P4560', 'P4653', 'P4772', 'P4884',
            'P4919', 'P5318', 'P5331', 'P5626', 'P5662', 'P6259', 'P6320', 'P6323', 'P6326']

