# Datasets
datasets:
    neurips2021:
        organism: 'hg38'
        url: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE194122&format=file&file=GSE194122%5Fopenproblems%5Fneurips2021%5Fmultiome%5FBMMC%5Fprocessed%2Eh5ad%2Egz'
        cases:
            blood:
                celltypes: 'HSC;MK/E prog;Proerythroblast;Erythroblast;Normoblast'
                n_hvg: 2048
                n_hvr: 8192
            small:
                celltypes: 'HSC;MK/E prog;Proerythroblast;Erythroblast;Normoblast'
                n_hvg: 512
                n_hvr: 1024
    pbmc10k:
        organism: 'hg38'
        url:
            matrix: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5'
            peak_annot: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_peak_annotation.tsv'
            atac_frags: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz'
            atac_index: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz.tbi'
