# Datasets
neurips2021:
    organism: "human"
    data: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE194122&format=file&file=GSE194122%5Fopenproblems%5Fneurips2021%5Fmultiome%5FBMMC%5Fprocessed%2Eh5ad%2Egz"
    trajectories:
        blood:
            celltypes: 'HSC;MK/E prog;Proerythroblast;Erythroblast;Normoblast'
            n_hvg: 2048
            n_downsample: 0
            celloracle:
                thr_coaccess: 0.8
                fpr: 0.02
                thr_motif_score: 10
                thr_edge_pval: 0.001
                thr_top_edges: 2000
        small:
            celltypes: 'HSC;MK/E prog;Proerythroblast;Erythroblast;Normoblast'
            n_hvg: 512
            n_downsample: 2
            celloracle:
                thr_coaccess: 0.8
                fpr: 0.02
                thr_motif_score: 10
                thr_edge_pval: 0.001
                thr_top_edges: 2000
            pando:
                p_thresh: 0.05
                rsq_thresh: 0.1
                nvar_thresh: 10
                exclude_exons: FALSE

pbmc10k:
    organism: "human"
    data:
        matrix: "https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5"
        peak_annot: "https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_peak_annotation.tsv"
        atac_frags: "https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz"
        atac_index: "https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz.tbi"
