methods:
    celloracle:
        k: 20
        thr_coaccess: 0.8
        ext: 500000
        fpr: 0.02
        blen: 200
        tfb_thr: 10
        a: 10
        p: 0.001
        n: 2000
    figr:
        ext: 500000
        thr_p2g_pval: 0.1
        ncres: 10
        cellK: 10
        dorcK: 10
        thr_score: 2
    granie:
        ext: 500000
        thr_fdr: 0.2
    pando:
        exclude_exons: 'TRUE'
        ext: 500000
        thr_corr: 0.05
        p_thresh: 0.1
        rsq_thresh: 0.05
        nvar_thresh: 2
        min_genes_per_module: 3

# Datasets
datasets:
    pbmc10k:
        organism: 'hg38'
        url:
            matrix: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5'
            peak_annot: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_peak_annotation.tsv'
            atac_frags: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz'
            atac_index: 'https://cf.10xgenomics.com/samples/cell-arc/1.0.0/pbmc_granulocyte_sorted_10k/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz.tbi'
        cases:
            tcell:
                celltypes: 'CD4 TCM;CD4 Naive;CD8 Naive;Treg;CD4 TEM;MAIT;CD8 TEM_1;CD8 TEM_2;gdT;CD8 TEM_2'
                n_hvg: 2048
                n_hvr: 16384
            bcell:
                celltypes: 'Naive B;Intermediate B;Memory B'
                n_hvg: 4096
                n_hvr: 16384
                root: 'Naive B'
            mono:
                celltypes: 'CD14 Mono;CD16 Mono'
                n_hvg: 4096
                n_hvr: 16384
                root: 'CD14 Mono'
            all:
                celltypes: 'all'
                n_hvg: 16384
                n_hvr: 65536
    reprofibro:
        organism: 'hg38'
        url:
            tar: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file'
            barcodes: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file&file=GSE242419%5Fmultiome%2EATAC%2ERNA%2Ebarcode%2Emap%2Etsv%2Egz'
            genes: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE242419&format=file&file=GSE242419%5Fmultiome%5Fgenes%2Etsv%2Egz'
            annot: 'https://zenodo.org/records/8313962/files/multiome.zip?download=1'
        cases:
            all:
                celltypes: 'all'
                n_hvg: 8192
                n_hvr: 32768
                root: 'Fibroblast-like'
    pitupair:
        organism: 'hg38'
        url:
            frags: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391776/suppl/GSM5391776%5FHF1M%2DCryo%5Fatac%5Ffragments%2Etsv%2Egz'
            multi: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391776/suppl/GSM5391776%5FHF1M%2DCryo%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
    pitunpair:
        organism: 'hg38'
        url:
            atac_frags: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391768/suppl/GSM5391768%5FHFA1P%5Ffragments%2Etsv%2Egz'
            peaks: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391768/suppl/GSM5391768%5FHFA1P%5Ffiltered%5Fpeak%5Fbc%5Fmatrix%2Eh5'
            rna_mtx: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391775/suppl/GSM5391775%5FHF1P%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            atac_meta: 'https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5391nnn/GSM5391768/suppl/GSM5391768%5FHFA1P%5Fsinglecell%2Ecsv%2Egz'
            celltypes: 'https://heibox.uni-heidelberg.de/f/d36511f7f94947859564/?dl=1'
    heartatlas:
        organism: 'hg38'
        url:
            tar: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/fragments.tar'
            anndata: 'https://cellgeni.cog.sanger.ac.uk/heartcellatlas/v2/Global_raw.h5ad'
        batchIDs:
            - HCAHeart9508627_HCAHeart9508819
            - HCAHeart9508628_HCAHeart9508820
            - HCAHeart9508629_HCAHeart9508821
            - HCAHeart9845431_HCAHeart9917173
            - HCAHeart9845432_HCAHeart9917174
            - HCAHeart9845433_HCAHeart9917175
            - HCAHeart9845434_HCAHeart9917176
            - HCAHeart9845435_HCAHeart9917177
            - HCAHeart9845436_HCAHeart9917178
            - HCAHeartST10773165_HCAHeartST10781062
            - HCAHeartST10773166_HCAHeartST10781063
            - HCAHeartST10773167_HCAHeartST10781064
            - HCAHeartST10773168_HCAHeartST10781065
            - HCAHeartST10773169_HCAHeartST10781446
            - HCAHeartST10773170_HCAHeartST10781447
            - HCAHeartST10773171_HCAHeartST10781448
            - HCAHeartST11064574_HCAHeartST11023239
            - HCAHeartST11064575_HCAHeartST11023240
            - HCAHeartST11064576_HCAHeartST11023241
            - HCAHeartST11064577_HCAHeartST11023242
            - HCAHeartST11350184_HCAHeartST11121842
            - HCAHeartST11350186_HCAHeartST11121844
            - HCAHeartST11350187_HCAHeartST11121845
            - HCAHeartST11350192_HCAHeartST11445769
            - HCAHeartST11350193_HCAHeartST11445770
            - HCAHeartST11350194_HCAHeartST11445771
            - HCAHeartST11350195_HCAHeartST11445772
            - HCAHeartST11350196_HCAHeartST11445773
            - HCAHeartST11350197_HCAHeartST11445774
            - HCAHeartST11350198_HCAHeartST11445775
            - HCAHeartST13146201_HCAHeartST13129134
            - HCAHeartST13146202_HCAHeartST13129135
            - HCAHeartST13146203_HCAHeartST13129136
            - HCAHeartST13146204_HCAHeartST13129137
            - HCAHeartST13146205_HCAHeartST13129138
            - HCAHeartST13146206_HCAHeartST13129139
            - HCAHeartST13146207_HCAHeartST13129140
            - HCAHeartST13146208_HCAHeartST13129141
            - HCAHeartST13168796_HCAHeartST13167740
            - HCAHeartST13180615_HCAHeartST13177112
            - HCAHeartST13180616_HCAHeartST13177113
            - HCAHeartST13180617_HCAHeartST13177114
            - HCAHeartST13180618_HCAHeartST13177115
            - HCAHeartST13180619_HCAHeartST13177116
            - HCAHeartST13189995_HCAHeartST13188800
            - HCAHeartST13189996_HCAHeartST13188801
            - HCAHeartST13189997_HCAHeartST13188802

    brain:
        organism: 'hg38'
        url:
            frags_smpl1: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5818649&format=file&file=GSM5818649%5FC16007%5Fatac%5Ffragments%2Etsv%2Egz'
            multi_smpl1: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5818649&format=file&file=GSM5818649%5FC16007%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            frags_smpl2: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5818673&format=file&file=GSM5818673%5FYC4345%5Fatac%5Ffragments%2Etsv%2Egz'
            multi_smpl2: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSM5818673&format=file&file=GSM5818673%5FYC4345%5Ffiltered%5Ffeature%5Fbc%5Fmatrix%2Eh5'
            full_dataset: 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE193688&format=file'
            annot: 'https://heibox.uni-heidelberg.de/f/05637a872a384155a951/?dl=1'

